%windmill and hydro_plant and caloric will be used
control(c).
c(c,i1,10).%L_cur
c(c,i2,30).%L_demand
c(c,i3,full).%S_storage
c(c,i4,20).%S_wind
w_charge(8).
expect_c(c,i1,10).%L_cur
expect_c(c,i2,30).%L_demand
expect_c(c,i3,full).%S_storage
expect_c(c,i4,20).%S_wind

windmill(w).
c_max(w,5).
storage_plant(psh).
c_max(psh,5).
caloric_plant(f).
c_max(f,50).

expect_c(c,o2,5).
expect_c(c,o1,5).
expect_c(c,o3,10).
expect_c(c,o4,1).
expect_c(c,o5,0).
